### ISSUE TITLE
Can't disable autostart with new user

### ISSUE THREAD

**Issue by ajgringo619** [endeavouros-team/welcome#1]
(Brand-new setup: GNOME desktop, using the latest RC6 Galileo ISO)

I created a new user to run some tests. When the initial **Welcome** screen popped up, I could not select the "Don't show me anymore" button - it just did nothing. After I selected a couple of other working options, I was able to click the offending button again.

Any ideas? What else do you need from me?

**Comment by manuel-192** [comment]
Thanks, we can continue at the forum if still needed.
