### ISSUE TITLE
wrong country language code

### ISSUE THREAD

**Issue by bittin** [endeavouros-team/welcome#2]
sv_NO = NO is for Norway and not Sweden should be sv_SE in the change language dialog box

**Comment by killajoe** [comment]
@manuel-192 ?

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/welcome/blob/0540cf781717893e133579ecfdb2d3d647a55556/welcome#L1318

**Comment by bittin** [comment]
@killajoe made the two needed PRs to fix this

**Comment by manuel-192** [comment]
Thanks! Fixed and released, closing.
