### ISSUE TITLE
More language translations are needed,please!

### ISSUE THREAD

**Issue by wkr111** [endeavouros-team/welcome#4]
Hi!I'm from China,and my friends are interested in EndeavourOS.But there's a hard part here for them,they are not very familiar with the English language.Because of this,I come here to Make this request.Hope you can do this,thanks!

**Comment by manuel-192** [comment]
Hi!

Thanks for contacting us!
The language translations for the Welcome app are mostly made by our community members. So help with the translations is greatly appreciated. If possible, would *you* be willing to help? Or do you know anyone who could help? Please let me know.

The best and fastest way to contact us is at our forum, https://forum.endeavouros.com.

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/PKGBUILDS/tree/master/eos-translations

There you can find they files we use in the EndeavourOS applications, in addition there is this:
For the custom parts of the installer itself (calamares):
https://github.com/endeavouros-team/calamares/blob/calamares/data/eos/calamares-translations.txt

But from what i see calamares has all files translated, but they should be reviewed in cas esomeone is able to do that, most of them are translated by tools only.

**Comment by wkr111** [comment]
> https://github.com/endeavouros-team/PKGBUILDS/tree/master/eos-translations
> 
> There you can find they files we use in the EndeavourOS applications, in addition there is this: For the custom parts of the installer itself (calamares): https://github.com/endeavouros-team/calamares/blob/calamares/data/eos/calamares-translations.txt
> 
> But from what i see calamares has all files translated, but they should be reviewed in cas esomeone is able to do that, most of them are translated by tools only.

Thanks for your help and apply!But I don't mean on the installer.What I mean is that after the installation is complete, the program with the name Welcome doesn't have a button to change the language, only English.

**Comment by wkr111** [comment]
> https://github.com/endeavouros-team/PKGBUILDS/tree/master/eos-translations
> 
> There you can find they files we use in the EndeavourOS applications, in addition there is this: For the custom parts of the installer itself (calamares): https://github.com/endeavouros-team/calamares/blob/calamares/data/eos/calamares-translations.txt
> 
> But from what i see calamares has all files translated, but they should be reviewed in cas esomeone is able to do that, most of them are translated by tools only.

Thanks for your help and apply!But I don't mean on the installer.What I mean is that after the installation is complete, the program with the name Welcome doesn't have a button to change the language, only English.

**Comment by wkr111** [comment]
> https://github.com/endeavouros-team/PKGBUILDS/tree/master/eos-translations
> 
> There you can find they files we use in the EndeavourOS applications, in addition there is this: For the custom parts of the installer itself (calamares): https://github.com/endeavouros-team/calamares/blob/calamares/data/eos/calamares-translations.txt
> 
> But from what i see calamares has all files translated, but they should be reviewed in cas esomeone is able to do that, most of them are translated by tools only.

Thanks!

**Comment by manuel-192** [comment]
Thanks for the report!
This bug should be fixed now in `welcome` version 24-1.

In case the issue still exists in welcome 24-1, please re-open this thread.

**Comment by manuel-192** [comment]
Closing for now.
