### ISSUE TITLE
Icons in Personalizing Welcome

### ISSUE THREAD

**Issue by biloucat** [endeavouros-team/welcome#5]
Icons in command buttons in Personalizing Welcome don't show up with new api.
The old api works well

**Comment by killajoe** [comment]
api?
You will need to give some more detail about teh issue you have and exactly what you have done to cause this.

**Comment by biloucat** [comment]
According to https://github.com/endeavouros-team/welcome/blob/main/Adding-own-commands.md#new-simpler-api:

In my ~/.config/welcome-own-cmds.conf:

**with**:
local welcome_own_commands=(
    --field="FeatherPad!featherpad!Lightweight Qt text editor":fbtn	"featherpad"
)
--> featherpad icon appear in Command Button

**with**:
personal_commands_add "featherpad" \
                      "FeatherPad" \
                      "featherpad" \
                      "Lightweight Qt text editor"
--> featherpad icon don't appear in Command Button
![Capture d’écran_2024-01-21_14-55-00](https://github.com/endeavouros-team/welcome/assets/18089011/000022f6-a6e5-4674-8134-cede6734a7a0)

**Comment by manuel-192** [comment]
Here's an example about a definition with `akm`:
```
personal_commands_init no "" yes

personal_commands_add "akm"\
                      "A Kernel Manager"\
                      "system-software-install"\
                      "Simple kernel manager and info source"
```
Not visible in your example, but maybe you forgot the line continuation backslash from those lines?
Or did you have the `personal_commands_init` line?

Reference: https://github.com/endeavouros-team/welcome/blob/main/Adding-own-commands.md

Edit: checked welcome's code again, and you're right, the icon parameter is not properly handled. I'll fix it as soon as possible.
Thanks for the report!

**Comment by biloucat** [comment]
Thanks for the Welcome update version 24.1-1 but the icon of "Commandes personnelles tirer&glisser" is  still incorrect:
![Capture d’écran_2024-01-21_20-49-28](https://github.com/endeavouros-team/welcome/assets/18089011/02140ac9-8816-4790-8ebd-719db8385a21)
![Capture d’écran_2024-01-21_21-33-55](https://github.com/endeavouros-team/welcome/assets/18089011/949907c5-c2c8-47fd-8842-e4dfde19abdc)

**Comment by biloucat** [comment]
Thanks for the Welcome update version 24.2-1 : All seems perfect !
