### ISSUE TITLE
Cyrillic (and possibly some other) languages unreadable in EOS tools when using the gnome desktop environment

### ISSUE THREAD

**Issue by blind-confused** [endeavouros-team/welcome#6]
as one of the devs already explained to me, it's because kgx (the new gnome terminal) is not supported to be used by EOS tools, that's why it goes with the fallback terminal, which is xterm. But... if your system has a language that is not using Latin alphabet (like anything Cyrillic), this is what it ends up looking like:
![Снимок экрана от 2024-04-10 02-39-51](https://github.com/endeavouros-team/welcome/assets/157859470/18b47c3f-760b-4a5c-90bd-13c7c1fe4100)
this disrupts daily system maintenance tasks, like EOS mirror updating, pacnew file management, etc.
a lot of users might not know that they just need to install another terminal, so they might never know how to fix the issue.
I'm not sure whether any other languages are turned into squares, perhaps Chinese, Hindi, other non-Latin ones might be unreadable too? 
so... perhaps using another terminal as the fallback option would be better? Unless support for all languages can be ensured in xterm somehow? or perhaps support for kgx should be added?
(as a side note, xterm also never follows dark mode either :D)

**Comment by dalto8** [comment]
Last I looked at kgx, it didn't support the terminal closing after a command is run(As virtually every other terminal could do).  This made it a poor host for most of our tasks.  Has that support been added?

**Comment by killajoe** [comment]
seems it simply falls back to xterm, what indeed looks very ugly and poorly decided from the outside world ;)

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/eos-bash-shared/blob/443c81b64dc4b237fc1ae4c346903f062935b96b/eos-script-lib-yad.conf#L14

and:

https://github.com/endeavouros-team/eos-bash-shared/blob/443c81b64dc4b237fc1ae4c346903f062935b96b/eos-script-lib-yad#L347

**Comment by dalto8** [comment]
I suppose we could install an additional terminal with gnome if kgx still lacks support.

**Comment by killajoe** [comment]
> Last I looked at kgx, it didn't support the terminal closing after a command is run

let me check.. if it is even the same anymore..

**Comment by dalto8** [comment]
I just tested it.  It still appears to be the case.

**Comment by killajoe** [comment]
![Bildschirmfoto vom 2024-04-15 15-24-37](https://github.com/endeavouros-team/welcome/assets/16797647/283a9e05-8a4b-4088-b60c-6313f9344384)
same... it does not close.

**Comment by dalto8** [comment]
Looks like it is a long standing issue: https://gitlab.gnome.org/GNOME/console/-/issues/135

I guess our options are:
* Leave things the way they are
* Switch back to gnome terminal
* Add an additional terminal application as a fallback for commands.

**Comment by killajoe** [comment]
Would be good to add one that supports all languages and is running on wayland and X11 the same ? 

> Looks like it is a long standing issue: https://gitlab.gnome.org/GNOME/console/-/issues/135

I do not see any dev responding there anyway..

**Comment by manuel-192** [comment]
This is the list of supported terminals (in file `eos-script-lib-yad`):
```
        xfce4-terminal
        konsole
        gnome-terminal
        mate-terminal
        lxterminal
        deepin-terminal
        terminator
        qterminal
        alacritty
        tilix
        termite
        xterm
        kitty
        terminology
        sakura
 ```
in the order they are tried. These can close the terminal in the end.
The only way to prefer another terminal outside this list is by setting  a value to
variable EOS_YAD_TERMINAL in file `/etc/eos-script-lib-yad.conf`.

As @dalto8 said, we could consider installing gnome-terminal for gnome systems.

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/calamares/commit/8ef0c6757d0fca4e8209ba7e6873b0a0d8227b79

**Comment by killajoe** [comment]
![2024-04-20_21-39](https://github.com/endeavouros-team/welcome/assets/16797647/aafb5403-d9c8-45a1-a9d9-7059fff733e6)
![2024-04-20_21-38](https://github.com/endeavouros-team/welcome/assets/16797647/a30703e8-9249-49b4-a116-a3e118c8b360)
Tested on Release candidate ;)
